<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

# **Hands-on Lab: Interactive Visual Analytics with Folium**

Estimated time needed: **40** minutes

The launch success rate may depend on many factors such as payload mass, orbit type, and so on. It may also depend on the location and proximities of a launch site, i.e., the initial position of rocket trajectories. Finding an optimal location for building a launch site certainly involves many factors and hopefully we could discover some of the factors by analyzing the existing launch site locations.

In the previous exploratory data analysis labs, you have visualized the SpaceX launch dataset using `matplotlib` and `seaborn` and discovered some preliminary correlations between the launch site and success rates. In this lab, you will be performing more interactive visual analytics using `Folium`.

## Objectives

This lab contains the following tasks:

*   **TASK 1:** Mark all launch sites on a map
*   **TASK 2:** Mark the success/failed launches for each site on the map
*   **TASK 3:** Calculate the distances between a launch site to its proximities

After completed the above tasks, you should be able to find some geographical patterns about launch sites.

Let's first import required Python packages for this lab:

In [1]:
import piplite
await piplite.install(['folium'])
await piplite.install(['pandas'])

In [2]:
import folium
import pandas as pd

In [3]:
# Import folium MarkerCluster plugin
from folium.plugins import MarkerCluster
# Import folium MousePosition plugin
from folium.plugins import MousePosition
# Import folium DivIcon plugin
from folium.features import DivIcon

If you need to refresh your memory about folium, you may download and refer to this previous folium lab:

[Generating Maps with Python](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/labs/v4/DV0101EN-Exercise-Generating-Maps-in-Python.ipynb)

In [4]:
## Task 1: Mark all launch sites on a map
launch_sites = [
    {"name": "Site 1", "lat": 28.5623, "lon": -80.5774},
    {"name": "Site 2", "lat": 34.6321, "lon": -120.6107},
    {"name": "Site 3", "lat": 28.5734, "lon": -80.6469},
    {"name": "Site 4", "lat": 34.632, "lon": -120.610}
]

# Create a map centered around the average coordinates
map_center = [sum(site["lat"] for site in launch_sites) / len(launch_sites),
              sum(site["lon"] for site in launch_sites) / len(launch_sites)]

launch_map = folium.Map(location=map_center, zoom_start=5)

# Add markers for each launch site
for site in launch_sites:
    folium.Marker(
        location=[site["lat"], site["lon"]],
        popup=site["name"]
    ).add_to(launch_map)

# Display the map
launch_map

First, let's try to add each site's location on a map using site's latitude and longitude coordinates

The following dataset with the name `spacex_launch_geo.csv` is an augmented dataset with latitude and longitude added for each site.

In [5]:
# Download and read the `spacex_launch_geo.csv`
from js import fetch
import io

URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv'
resp = await fetch(URL)
spacex_csv_file = io.BytesIO((await resp.arrayBuffer()).to_py())
spacex_df=pd.read_csv(spacex_csv_file)

Now, you can take a look at what are the coordinates for each site.

In [6]:
# Select relevant sub-columns: `Launch Site`, `Lat(Latitude)`, `Long(Longitude)`, `class`
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

Above coordinates are just plain numbers that can not give you any intuitive insights about where are those launch sites. If you are very good at geography, you can interpret those numbers directly in your mind. If not, that's fine too. Let's visualize those locations by pinning them on a map.

We first need to create a folium `Map` object, with an initial center location to be NASA Johnson Space Center at Houston, Texas.

In [7]:
# Start location is NASA Johnson Space Center
nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

We could use `folium.Circle` to add a highlighted circle area with a text label on a specific coordinate. For example,

In [8]:
# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

and you should find a small yellow circle near the city of Houston and you can zoom-in to see a larger circle.

Now, let's add a circle for each launch site in data frame `launch_sites`

*TODO:*  Create and add `folium.Circle` and `folium.Marker` for each launch site on the site map

An example of folium.Circle:

`folium.Circle(coordinate, radius=1000, color='#000000', fill=True).add_child(folium.Popup(...))`

An example of folium.Marker:

`folium.map.Marker(coordinate, icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'label', ))`

In [10]:
# Initial the map
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)
# For each launch site, add a Circle object based on its coordinate (Lat, Long) values.
# In addition, add Launch site name as a popup label

launch_sites = [
    {"name": "CCAFS LC-40", "lat": 28.562302, "lon": -80.577356},
    {"name": "CCAFS SLC-40", "lat": 28.563197, "lon": -80.576820},
    {"name": "KSC LC-39A", "lat": 28.573255, "lon": -80.646895},
    {"name": "VAFB SLC-4E", "lat": 34.632834, "lon": -120.610745}
]

# Create a map centered around the average location of all sites
map_center = [sum(site["lat"] for site in launch_sites) / len(launch_sites),
              sum(site["lon"] for site in launch_sites) / len(launch_sites)]

site_map = folium.Map(location=map_center, zoom_start=5)

# Add both Circle and Marker for each launch site
for site in launch_sites:
    # Add a marker
    folium.Marker(
        location=[site["lat"], site["lon"]],
        popup=site["name"]
    ).add_to(site_map)
    
    # Add a circle with radius in meters (e.g., 5000 m)
    folium.Circle(
        radius=5000,
        location=[site["lat"], site["lon"]],
        color='blue',
        fill=True,
        fill_color='blue',
        fill_opacity=0.1
    ).add_to(site_map)

# Display the map
site_map

The generated map with marked launch sites should look similar to the following:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_markers.png">
</center>

Now, you can explore the map by zoom-in/out the marked areas
, and try to answer the following questions:

*   Are all launch sites in proximity to the Equator line?
*   Are all launch sites in very close proximity to the coast?

Also please try to explain your findings.

all launchh sites are in proximity to the equator line but not are very 
close proximity to the coast. VAFB SLC-4E and CCAFS SLC-40 are closer to
the coast but KSC LC-39A is not.

In [21]:
# Task 2: Mark the success/failed launches for each site on the map
sites = [
    {"name": "CCAFS LC-40", "lat": 28.562302, "lon": -80.577356, 'status': 'success'},
    {"name": "CCAFS SLC-40", "lat": 28.563197, "lon": -80.576820, 'status': 'failed'},
    {"name": "KSC LC-39A", "lat": 28.573255, "lon": -80.646895, 'status': 'success'},
    {"name": "VAFB SLC-4E", "lat": 34.632834, "lon": -120.610745, 'status': 'failed'}
]

# Create a map centered around the sites
m = folium.Map(location=[29, -96], zoom_start=6)

# Add markers
for site in sites:
    color = 'green' if site['status'] == 'success' else 'red'
    folium.Marker(
        location=[site['lat'], site['lon']],
        popup=f"{site['name']} - {site['status']}",
        icon=folium.Icon(color=color)
    ).add_to(m)

# Display the map
site_map

Next, let's try to enhance the map by adding the launch outcomes for each site, and see which sites have high success rates.
Recall that data frame spacex_df has detailed launch records, and the `class` column indicates if this launch was successful or not

In [22]:
spacex_df.tail(10)

     Launch Site        Lat       Long  class
46    KSC LC-39A  28.573255 -80.646895      1
47    KSC LC-39A  28.573255 -80.646895      1
48    KSC LC-39A  28.573255 -80.646895      1
49  CCAFS SLC-40  28.563197 -80.576820      1
50  CCAFS SLC-40  28.563197 -80.576820      1
51  CCAFS SLC-40  28.563197 -80.576820      0
52  CCAFS SLC-40  28.563197 -80.576820      0
53  CCAFS SLC-40  28.563197 -80.576820      0
54  CCAFS SLC-40  28.563197 -80.576820      1
55  CCAFS SLC-40  28.563197 -80.576820      0

Next, let's create markers for all launch records.
If a launch was successful `(class=1)`, then we use a green marker and if a launch was failed, we use a red marker `(class=0)`

Note that a launch only happens in one of the four launch sites, which means many launch records will have the exact same coordinate. Marker clusters can be a good way to simplify a map containing many markers having the same coordinate.

Let's first create a `MarkerCluster` object

In [23]:
marker_cluster = MarkerCluster()

*TODO:* Create a new column in `spacex_df` dataframe called `marker_color` to store the marker colors based on the `class` value

In [24]:
def assign_marker_color(Class_value):
    if Class_value == 1:
# If class=1, marker_color value will be green
        return 'green'
    else:
# If class=0, marker_color value will be red
        return 'red'

# Apply a function to check the value of `class` column
spacex_df['marker_color'] = spacex_df['class'].apply(assign_marker_color)
spacex_df.head()

   Launch Site        Lat       Long  class marker_color
0  CCAFS LC-40  28.562302 -80.577356      0          red
1  CCAFS LC-40  28.562302 -80.577356      0          red
2  CCAFS LC-40  28.562302 -80.577356      0          red
3  CCAFS LC-40  28.562302 -80.577356      0          red
4  CCAFS LC-40  28.562302 -80.577356      0          red

*TODO:* For each launch result in `spacex_df` data frame, add a `folium.Marker` to `marker_cluster`

In [25]:
# Add marker_cluster to current site_map
site_map.add_child(marker_cluster)
# for each row in spacex_df data frame
# create a Marker object with its coordinate
# and customize the Marker's icon property to indicate if this launch was successed or failed, 
# e.g., icon=folium.Icon(color='white', icon_color=row['marker_color']
for index, record in spacex_df.iterrows():
    # TODO: Create and add a Marker cluster to the site map
    marker = folium.Marker(
        location=[record['Lat'], record['Long']], 
        icon=folium.Icon(color='red', icon_color=record['marker_color'])  
    )
    marker_cluster.add_child(marker)

site_map

Your updated map may look like the following screenshots:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster.png">
</center>

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster_zoomed.png">
</center>

From the color-labeled markers in marker clusters, you should be able to easily identify which launch sites have relatively high success rates.

In [26]:
# TASK 3: Calculate the distances between a launch site to its proximities
import math

def haversine_distance(lat1, lon1, lat2, lon2):
    # Radius of Earth in kilometers
    R = 6371.0

    # Convert degrees to radians
    lat1_rad = math.radians(lat1)
    lon1_rad = math.radians(lon1)
    lat2_rad = math.radians(lat2)
    lon2_rad = math.radians(lon2)

    # Differences
    dlat = lat2_rad - lat1_rad
    dlon = lon2_rad - lon1_rad

    # Haversine formula
    a = math.sin(dlat/2)**2 + math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon/2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

    distance = R * c
    return distance

# Example usage:
launch_site_lat = 28.5623
launch_site_lon = -80.5774

# Suppose you have a proximity location
proximity_lat = 28.573255
proximity_lon = -80.646895

distance_km = haversine_distance(launch_site_lat, launch_site_lon, proximity_lat, proximity_lon)
print(f"Distance: {distance_km:.2f} km")

Distance: 6.90 km

Next, we need to explore and analyze the proximities of launch sites.

Let's first add a `MousePosition` on the map to get coordinate for a mouse over a point on the map. As such, while you are exploring the map, you can easily find the coordinates of any points of interests (such as railway)

In [27]:
# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

Now zoom in to a launch site and explore its proximity to see if you can easily find any railway, highway, coastline, etc. Move your mouse to these points and mark down their coordinates (shown on the top-left) in order to the distance to the launch site.

Now zoom in to a launch site and explore its proximity to see if you can easily find any railway, highway, coastline, etc. Move your mouse to these points and mark down their coordinates (shown on the top-left) in order to the distance to the launch site.

In [28]:
from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

*TODO:* Mark down a point on the closest coastline using MousePosition and calculate the distance between the coastline point and the launch site.

In [29]:
# Haversine distance function
def calculate_distance(lat1, lon1, lat2, lon2):
    R = 6371.0  # Earth radius in km
    lat1_rad, lon1_rad = math.radians(lat1), math.radians(lon1)
    lat2_rad, lon2_rad = math.radians(lat2), math.radians(lon2)
    dlat = lat2_rad - lat1_rad
    dlon = lon2_rad - lon1_rad
    a = math.sin(dlat/2)**2 + math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon/2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    return R * c

# Coordinates of launch site
launch_site_lat, launch_site_lon = 28.5623, -80.5774

# Coordinates of closest coastline (example)
coastline_lat, coastline_lon = 28.56367, -80.57163

# Calculate distance
distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)
print(f"Distance to coastline: {distance_coastline:.2f} km")

# Create map centered around launch site
site_map = folium.Map(location=[launch_site_lat, launch_site_lon], zoom_start=13)

# Add MousePosition plugin to get coordinates interactively
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=5,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)
site_map.add_child(mouse_position)

# Add markers for launch site and coastline
folium.Marker(
    location=[launch_site_lat, launch_site_lon],
    popup='Launch Site',
    icon=folium.Icon(color='red')
).add_to(site_map)

folium.Marker(
    location=[coastline_lat, coastline_lon],
    popup=f'Closest Coastline\nDistance: {distance_coastline:.2f} km',
    icon=folium.Icon(color='blue')
).add_to(site_map)

site_map

Distance to coastline: 0.58 km

In [31]:
# Haversine distance function
def calculate_distance(lat1, lon1, lat2, lon2):
    R = 6371.0  # Earth radius in km
    lat1_rad, lon1_rad = math.radians(lat1), math.radians(lon1)
    lat2_rad, lon2_rad = math.radians(lat2), math.radians(lon2)
    dlat = lat2_rad - lat1_rad
    dlon = lon2_rad - lon1_rad
    a = math.sin(dlat/2)**2 + math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon/2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    return R * c

# Coordinates of launch site and closest coastline point
launch_site = [28.5623, -80.5774]
coastline_point = [28.56367, -80.57163]

# Calculate distance
distance = calculate_distance(launch_site[0], launch_site[1], coastline_point[0], coastline_point[1])

# Create map centered between launch site and coastline
map_center = [(launch_site[0] + coastline_point[0]) / 2, (launch_site[1] + coastline_point[1]) / 2]
site_map = folium.Map(location=map_center, zoom_start=13)

# Add launch site marker
folium.Marker(
    location=launch_site,
    popup='Launch Site',
    icon=folium.Icon(color='red')
).add_to(site_map)

# Add marker for closest coastline point
folium.Marker(
    location=coastline_point,
    icon=DivIcon(
        icon_size=(150, 36),
        icon_anchor=(0, 0),
        html=f'<div style="font-size: 12px; color:#d35400;"><b>{distance:.2f} KM</b></div>',
    )
).add_to(site_map)

site_map

*TODO:* Draw a `PolyLine` between a launch site to the selected coastline point

In [32]:
# Coordinates for launch site and coastline point
launch_site = [28.5623, -80.5774]
coastline_point = [28.56367, -80.57163]

# Create the map centered between the two points
map_center = [(launch_site[0] + coastline_point[0]) / 2, (launch_site[1] + coastline_point[1]) / 2]
site_map = folium.Map(location=map_center, zoom_start=13)

# Add markers for launch site and coastline point
folium.Marker(location=launch_site, popup='Launch Site', icon=folium.Icon(color='red')).add_to(site_map)
folium.Marker(location=coastline_point, popup='Coastline Point', icon=folium.Icon(color='blue')).add_to(site_map)

# Create a PolyLine connecting the launch site and coastline point
coordinates = [launch_site, coastline_point]
lines = folium.PolyLine(locations=coordinates, weight=2, color='green')

# Add the PolyLine to the map
site_map.add_child(lines)

# Display the map
site_map

Your updated map with distance line should look like the following screenshot:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_distance.png">
</center>

*TODO:* Similarly, you can draw a line betwee a launch site to its closest city, railway, highway, etc. You need to use `MousePosition` to find the their coordinates on the map first

A railway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/railway.png">
</center>

A highway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/highway.png">
</center>

A city map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/city.png">
</center>

In [33]:
# Create a marker with distance to a closest city, railway, highway, etc.
# Draw a line between the marker to the launch site

# Haversine distance function
def calculate_distance(lat1, lon1, lat2, lon2):
    R = 6371.0  # Earth radius in km
    lat1_rad, lon1_rad = math.radians(lat1), math.radians(lon1)
    lat2_rad, lon2_rad = math.radians(lat2), math.radians(lon2)
    dlat = lat2_rad - lat1_rad
    dlon = lon2_rad - lon1_rad
    a = math.sin(dlat/2)**2 + math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon/2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    return R * c

# Coordinates of launch site
launch_site = [28.5623, -80.5774]

# Coordinates of closest features (example data)
features = {
    "Closest City": [28.573255, -80.646895],
    "Closest Railway": [28.5678, -80.5800],
    "Closest Highway": [28.5600, -80.5700],
    "Nearby Building": [28.5650, -80.5750]
}

# Create map centered at launch site
site_map = folium.Map(location=launch_site, zoom_start=13)

# Add launch site marker
folium.Marker(
    location=launch_site,
    popup='Launch Site',
    icon=folium.Icon(color='red')
).add_to(site_map)

# Loop through features to add markers with distance and draw lines
for name, coord in features.items():
    distance = calculate_distance(launch_site[0], launch_site[1], coord[0], coord[1])
    
    # Add marker with distance label using DivIcon
    folium.Marker(
        location=coord,
        icon=DivIcon(
            icon_size=(150, 36),
            icon_anchor=(0, 0),
            html=f'<div style="font-size: 12px; color:#1f77b4;"><b>{name}: {distance:.2f} KM</b></div>'
        )
    ).add_to(site_map)
    
    # Draw line from feature to launch site
    folium.PolyLine(
        locations=[launch_site, coord],
        weight=2,
        color='green',
        opacity=0.6
    ).add_to(site_map)

site_map

After you plot distance lines to the proximities, you can answer the following questions easily:

*   Are launch sites in close proximity to railways?
*   Are launch sites in close proximity to highways?
*   Are launch sites in close proximity to coastline?
*   Do launch sites keep certain distance away from cities?

Also please try to explain your findings.

# Next Steps:

Now you have discovered many interesting insights related to the launch sites' location using folium, in a very interactive way. Next, you will need to build a dashboard using Ploty Dash on detailed launch records.

## Authors

[Pratiksha Verma](https://www.linkedin.com/in/pratiksha-verma-6487561b1/)

<!--## Change Log--!>

<!--| Date (YYYY-MM-DD) | Version | Changed By      | Change Description      |
| ----------------- | ------- | -------------   | ----------------------- |
| 2022-11-09        | 1.0     | Pratiksha Verma | Converted initial version to Jupyterlite|--!>

### <h3 align="center"> IBM Corporation 2022. All rights reserved. <h3/>